name: BRUMCLASSICSMobile
options:
  bundleIdPrefix: com.brumclassics
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    CURRENT_PROJECT_VERSION: 14
    MARKETING_VERSION: 0.7.3
targets:
  BRUMCLASSICSMobile:
    type: application
    platform: iOS
    sources:
      - path: BRUMCLASSICSMobile
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brumclassics.mobile.ios
        PRODUCT_NAME: BRUMCLASSICSMobile
        INFOPLIST_FILE: BRUMCLASSICSMobile/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
    scheme:
      testTargets:
        - BRUMCLASSICSMobileTests
        - BRUMCLASSICSMobileUITests
  BRUMCLASSICSMobileTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BRUMCLASSICSMobileTests
    dependencies:
      - target: BRUMCLASSICSMobile
  BRUMCLASSICSMobileUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BRUMCLASSICSMobileUITests
    dependencies:
      - target: BRUMCLASSICSMobile
