plugins {
    id "com.android.application"
}

android {
    namespace "com.brumclassics.mobile"
    compileSdk 36

    defaultConfig {
        applicationId "com.brumclassics.mobile"
        minSdk 26
        targetSdk 36
        versionCode 27
        versionName "0.19.0"
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }
}
